Update GQE-emulator version and help options

diff --git a/start-gqe-old b/start-gqe-old
--- a/start-gqe-old
+++ b/start-gqe-old
@@ -49,16 +49,16 @@ extract_file() {
 }
 
 if [ ! -f "$HOME/storage/shared/.gqe-start/all_var.txt" ]; then
-echo "The configuration file is corrupted. Attempting to reconfigure..."
-download_file https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/initialization-v0.1-sh "fac9bc74a9825c2dc821255b3c9945287b2b9796704eca30df55fc1b47b46d32" "initialization-sh" "Initialization Script"
-mv $PREFIX/tmp/initialization-v0.1-sh .
-sed -n '147,172p' initialization-v0.1-sh | bash
-rm -f initialization-v0.1-sh
+  echo "The configuration file is corrupted. Attempting to reconfigure..."
+  download_file https://raw.githubusercontent.com/ocnedkf/GQE-emulator/refs/heads/v0.3-beta/initialization-v0.1-sh "fac9bc74a9825c2dc821255b3c9945287b2b9796704eca30df55fc1b47b46d32" "initialization-sh" "Initialization Script"
+  mv $PREFIX/tmp/initialization-v0.1-sh .
+  sed -n '147,172p' initialization-v0.1-sh | bash
+  rm -f initialization-v0.1-sh
 fi
 
 if ! source "$HOME/storage/shared/.gqe-start/all_var.txt"; then
-echo "Failed to import environment variables! Please check whether /storage/emulated/0/.gqe-start/all_var.txt exists"
-exit 1
+  echo "Failed to import environment variables! Please check whether /storage/emulated/0/.gqe-start/all_var.txt exists"
+  exit 1
 fi
 
 show_info() {
@@ -69,12 +69,12 @@ GQE-emulator by ocnedkf
 
 GQE-emulator is an emulator capable of running Windows x86_64 applications.
 
-More details: https://github.com/ocnedkf/GQE-emulator/tree/v0.3-beta
+More details: https://github.com/ocnedkf/GQE-emulator/tree/v0.3.1-beta
 EOF
 }
 
 show_version() {
-echo "v0.3-beta"
+echo "v0.3.1-beta"
 }
 
 show_help() {
@@ -83,10 +83,11 @@ cat << EOF
 
 usage : start-gqe [option]
 
-        start-gqe               Launch GQE normally
-        start-gqe -v/--version  Print version info then exit
-        start-gqe -h/--help     Print introduction and help info then exit
-        start-gqe -f/--fix      Attempt to repair the Wine prefix
+        start-gqe                Launch GQE normally
+        start-gqe -na/--no-audio Launch GQE without audio support
+        start-gqe -v/--version   Print version info then exit
+        start-gqe -h/--help      Print introduction and help info then exit
+        start-gqe -f/--fix       Attempt to repair the Wine prefix
 EOF
 }
 
