更新 start-gqe

diff --git a/start-gqe b/start-gqe
--- a/start-gqe
+++ b/start-gqe
@@ -28,7 +28,12 @@ virgl_test_server --use-gles --use-egl-surfaceless &
 pkill -f termux-x11
 termux-x11 :13 >/dev/null 2>&1 &
 
-am start -n com.termux.x11/.MainActivity
+if am start -n com.termux.x11/.MainActivity; then
+sleep 0.8
+termux-x11-preference displayResolutionMode:exact displayResolutionExact:1024x768 || echo "Failed to set display resolution"
+else
+echo "Failed to start Termux:X11. Please ensure it is installed"
+fi
 
 env DXVK_ASYNC=1 BOX64_ASYNC=1 MESA_VK_DEVICE_SELECT=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_v.txt) VK_ICD_FILENAMES=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_f.txt) GALLIUM_DRIVER=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var.txt) WINEPREFIX=$HOME/.gqe-data LOCPATH=$HOME/.locale PULSE_SERVER=127.0.0.1 DXVK_HUD=1 MESA_NO_ERROR=1 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine64 explorer /desktop=shell,1024x768 Z:\\home\\storage\\shared\\.gqe-start\\start-gqe.bat >/dev/null 2>&1
 
