更新 start-gqe

diff --git a/start-gqe b/start-gqe
--- a/start-gqe
+++ b/start-gqe
@@ -41,7 +41,11 @@ virgl_test_server --use-gles --use-egl-surfaceless &
 pkill -f termux-x11
 termux-x11 :13 >/dev/null 2>&1 &
 
-am start -n com.termux.x11/.MainActivity || echo "Automatic redirection failed. Please ensure that Termux-x11 is installed"
+if am start -n com.termux.x11/.MainActivity; then
+termux-x11-preference displayResolutionMode:exact displayResolutionExact:1280x768 || echo "Failed to set display resolution"
+else
+    echo "Failed to start Termux:X11. Please ensure it is installed."
+fi
 
 env DXVK_ASYNC=1 BOX64_ASYNC=1 MESA_VK_DEVICE_SELECT=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_v.txt) VK_ICD_FILENAMES=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var_f.txt) GALLIUM_DRIVER=$(cat /data/data/com.termux/files/home/storage/shared/.gqe-start/mesa_var.txt) WINEPREFIX=$HOME/.gqe-data-v0.2 LOCPATH=$HOME/.locale PULSE_SERVER=127.0.0.1 DXVK_HUD=1 MESA_NO_ERROR=1 DISPLAY=:13 grun /data/data/com.termux/files/usr/glibc/bin/box64 /data/data/com.termux/files/usr/glibc/bin/wine explorer /desktop=shell,1024x768 Z:\\home\\storage\\shared\\.gqe-start\\start-gqe-v0.2.bat >/dev/null 2>&1
 
